services:
  - type: web
    name: crm-system
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        value: jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
      - key: DB_USER
        value: postgres.idoogxynhgasitjkfell
      - key: DB_PASSWORD
        value: lS2w5IqVli0GpoUS
      - key: APP_STORAGE_TYPE
        value: supabase
      - key: SUPABASE_STORAGE_URL
        value: https://idoogxynhgasitjkfell.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkb29neHluaGdhc2l0amtmZWxsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzQ0OTcyMywiZXhwIjoyMDkzMDI1NzIzfQ.L05fS8lJNo5MNl_HNdg2ZsQ8blipv5gtyUbxXGBxtqg
      - key: SUPABASE_BUCKET
        value: crm-uploads
      - key: BOOTSTRAP_SUPER_ADMIN_ENABLED
        value: "true"
      - key: BOOTSTRAP_SUPER_ADMIN_NAME
        value: Вадим
      - key: BOOTSTRAP_SUPER_ADMIN_SURNAME
        value: Минчик
      - key: BOOTSTRAP_SUPER_ADMIN_PATRONYMIC
        value: Андреевич
      - key: BOOTSTRAP_SUPER_ADMIN_LOGIN
        value: ztryuiorust
      - key: BOOTSTRAP_SUPER_ADMIN_PASSWORD
        value: "!22233loim"
      - key: BOOTSTRAP_SUPER_ADMIN_EMAIL
        value: vadim.minchik90@gmail.com
      - key: BOOTSTRAP_SUPER_ADMIN_PHONE
        value: "+375291573109"
