spring.application.name=crm-system
spring.thymeleaf.cache=false

server.servlet.session.timeout=3d
server.servlet.session.cookie.max-age=3d
server.servlet.session.cookie.http-only=true

# Локальный PostgreSQL (pgAdmin / дефолтный порт)
spring.datasource.url=jdbc:postgresql://localhost:5432/crm_system
spring.datasource.username=postgres
spring.datasource.password=Z1z2z3z4z
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=-1

file.upload-dir=uploads

app.storage.type=local

spring.output.ansi.enabled=always

spring.config.import=optional:classpath:application-local.properties
