spring.application.name=crm-system
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.blhhqnukyjlzfvnygpnr
spring.datasource.password=mmzZKHMgs9bB75Fa
spring.datasource.driver-class-name=org.postgresql.Driver
# Supabase ограничивает число подключений — пул не больше 5–10
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=300000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

supabase.url=https://blhhqnukyjlzfvnygpnr.supabase.co
supabase.service-role-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsaGhxbnVreWpsemZ2bnlncG5yIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDg5NTg0NywiZXhwIjoyMDg2NDcxODQ3fQ.ph882pykK5UcNIcV67nvBaPEzyjnFYfeVOzMLYprEeY
supabase.storage.bucket=passport-photos

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=-1


